### ISSUE TITLE
Server attempted to add player prior to sending player info

### ISSUE THREAD

**Issue by HC-Emro** [plasmoapp/plasmo-voice#365]
I have the latest version of the mod (2.0.6 fabric) on a papermc server (spigot) 1.19.4.
And it spams this message in logs of clients :

`Server attempted to add player prior to sending player info (Player id 97bf03be-a7d5-4cd0-980e-9f6c25e1752e)`

I don't know why.

**Comment by HC-Emro** [comment]
![image](https://github.com/plasmoapp/plasmo-voice/assets/56135028/9e58ee7f-7c87-4b67-a023-b3c34fd08a88)

**Comment by HC-Emro** [comment]
I use velocity for the voice chat proxy, and the plugin is also installed on the game server. Nothing special in server console.

**Comment by HC-Emro** [comment]
My bad, I just had to update the server plugins.

**Comment by HC-Emro** [comment]
Ok I just updated the plugin to 2.0.5 (velocity 2.0.6), it spams a lot less. I'll keep you informed.

**Comment by HC-Emro** [comment]
![image](https://github.com/plasmoapp/plasmo-voice/assets/56135028/5cf8aaab-562a-4010-93d2-275b262a1686)
Ultimately, it does the same with the new versions. A solution ?

**Comment by apehum** [comment]
Don't see how it can be caused by Plasmo Voice. Are you tried to remove Plasmo Voice from both client and server, and check if issue is still persist?

**Comment by HC-Emro** [comment]
I'll try asap.

**Comment by HC-Emro** [comment]
yes, sorry it's not from plasmo voice chat. my bad
